<?php

declare(strict_types=1);

namespace pixelwhiz\pathfinding;

use pocketmine\command\Command;
use pocketmine\command\CommandSender;
use pocketmine\plugin\PluginBase;
use SplPriorityQueue;

class Main extends PluginBase {

    protected function onEnable(): void
    {
        parent::onEnable();
        $openList = new SplPriorityQueue();
        $openList->setExtractFlags(SplPriorityQueue::EXTR_BOTH);
    }

    public function onCommand(CommandSender $sender, Command $command, string $label, array $args): bool
    {
        return parent::onCommand($sender, $command, $label, $args); // TODO: Change the autogenerated stub
    }

}
